# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amalgo < Formula
  desc "Create consolidated snapshots of source code for analysis, documentation, and sharing with LLMs."
  homepage "https://github.com/Broderick-Westrope/amalgo"
  version "0.4.0"
  license "GNU GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Broderick-Westrope/amalgo/releases/download/v0.4.0/amalgo_Darwin_x86_64.tar.gz"
      sha256 "7aadf57a60b81a516adee1b88626dce057ddbc5a8338f9954daf7a5493fd081c"

      def install
        bin.install "amalgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Broderick-Westrope/amalgo/releases/download/v0.4.0/amalgo_Darwin_arm64.tar.gz"
      sha256 "7dc51ca631a85be67b8e879847574db10dcaede24e6c6eef45ef5a13bfff3b8b"

      def install
        bin.install "amalgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Broderick-Westrope/amalgo/releases/download/v0.4.0/amalgo_Linux_x86_64.tar.gz"
        sha256 "04dbb68d6257fd9e7ab65cfb4c2af666ebce04bae6e029899d5f8f22546d8dcf"

        def install
          bin.install "amalgo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Broderick-Westrope/amalgo/releases/download/v0.4.0/amalgo_Linux_arm64.tar.gz"
        sha256 "c3dbf4cc187ecad3a400137b2393bc4b0bb8ef826794f84c57ff1fa685905758"

        def install
          bin.install "amalgo"
        end
      end
    end
  end

  test do
    system "#{bin}/amalgo --version"
  end
end
