# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amalgo < Formula
  desc "Create consolidated snapshots of source code for analysis, documentation, and sharing with LLMs."
  homepage "https://github.com/Broderick-Westrope/amalgo"
  version "0.3.0"
  license "GNU GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Broderick-Westrope/amalgo/releases/download/v0.3.0/amalgo_Darwin_x86_64.tar.gz"
      sha256 "8c0add4d852cd1728a82227e0cdf0d8daa44bfc97c2c852da00e07f60c8d1bc3"

      def install
        bin.install "amalgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Broderick-Westrope/amalgo/releases/download/v0.3.0/amalgo_Darwin_arm64.tar.gz"
      sha256 "f1e2706040e05d36a727824c324b32445dbe084e9900ecb445a93e542a20afce"

      def install
        bin.install "amalgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Broderick-Westrope/amalgo/releases/download/v0.3.0/amalgo_Linux_x86_64.tar.gz"
        sha256 "268b347f333ac4a4d0626803cfd1897c59ba6118a70ab9d03579dcb480c74214"

        def install
          bin.install "amalgo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Broderick-Westrope/amalgo/releases/download/v0.3.0/amalgo_Linux_arm64.tar.gz"
        sha256 "3aea7e5c3a57c95dd1f459396544efceaf80102ffd0dc5a63d1d25b8c15a53d2"

        def install
          bin.install "amalgo"
        end
      end
    end
  end

  test do
    system "#{bin}/amalgo --version"
  end
end
