# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muninn < Formula
  desc "Code search index and MCP server for your GitHub repos"
  homepage "https://github.com/Broderick-Westrope/muninn"
  version "0.5.0"
  license "MIT"

  depends_on "git"
  depends_on "universal-ctags"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Broderick-Westrope/muninn/releases/download/v0.5.0/muninn_0.5.0_darwin_amd64.tar.gz"
    sha256 "317c35577c0ab2c577912fdf2e86c8d4b2d047f1303518d34507cfda38c6eb73"

    define_method(:install) do
      bin.install "muninn"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Broderick-Westrope/muninn/releases/download/v0.5.0/muninn_0.5.0_darwin_arm64.tar.gz"
    sha256 "1f8892514d9cd833228eea507dfff28c5c39099b86cdae40efee54498e9c5d33"

    define_method(:install) do
      bin.install "muninn"
    end
  end

  def caveats
    <<~EOS
      Create ~/.config/muninn/config.json (see the README for the schema), then:
        muninn sync             # first sync: clone mirrors + build the index
        muninn sync --install   # schedule syncs via launchd (hourly by default)

      Add to your agent's MCP config:
        { "command": "muninn", "args": ["mcp"] }
    EOS
  end

  test do
    system "#{bin}/muninn", "--version"
  end
end
