# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muninn < Formula
  desc "Code search index and MCP server for your GitHub repos"
  homepage "https://github.com/Broderick-Westrope/muninn"
  version "0.3.0"
  license "MIT"

  depends_on "git"
  depends_on "universal-ctags"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Broderick-Westrope/muninn/releases/download/v0.3.0/muninn_0.3.0_darwin_amd64.tar.gz"
    sha256 "da97157fd26d6b7b639bdd7148f826d105fc2e6204fc12085108b4b30c4b79fd"

    define_method(:install) do
      bin.install "muninn"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Broderick-Westrope/muninn/releases/download/v0.3.0/muninn_0.3.0_darwin_arm64.tar.gz"
    sha256 "9f5080e3dc4d00a64db318fb43b4d27e7a79604c4c37eec070a80fdbb25b91b0"

    define_method(:install) do
      bin.install "muninn"
    end
  end

  def caveats
    <<~EOS
      Create ~/.config/muninn/config.json (see the README for the schema), then:
        muninn sync             # first sync: clone mirrors + build the index
        muninn sync --install   # schedule hourly syncs via launchd

      Add to your agent's MCP config:
        { "command": "muninn", "args": ["mcp"] }
    EOS
  end

  test do
    system "#{bin}/muninn", "--version"
  end
end
