# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muninn < Formula
  desc "Code search index and MCP server for your GitHub repos"
  homepage "https://github.com/Broderick-Westrope/muninn"
  version "0.2.0"
  license "MIT"

  depends_on "git"
  depends_on "universal-ctags"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Broderick-Westrope/muninn/releases/download/v0.2.0/muninn_0.2.0_darwin_amd64.tar.gz"
    sha256 "6feb681cd89a44f28a03d551a9068c8cfcafc12bd80b176e247b31a9c4039db3"

    define_method(:install) do
      bin.install "muninn"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Broderick-Westrope/muninn/releases/download/v0.2.0/muninn_0.2.0_darwin_arm64.tar.gz"
    sha256 "625a4ab2207368776baa7684b766eaa2755db0a0d7beb1281220371d271b5de0"

    define_method(:install) do
      bin.install "muninn"
    end
  end

  def caveats
    <<~EOS
      Create ~/.config/muninn/config.json (see the README for the schema), then:
        muninn sync             # first sync: clone mirrors + build the index
        muninn sync --install   # schedule hourly syncs via launchd

      Add to your agent's MCP config:
        { "command": "muninn", "args": ["mcp"] }
    EOS
  end

  test do
    system "#{bin}/muninn", "--version"
  end
end
