# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tetrigo < Formula
  desc "Play Tetris in your terminal."
  homepage "https://www.westrope.dev/"
  version "0.2.0"

  on_macos do
    url "https://github.com/Broderick-Westrope/tetrigo/releases/download/v0.2.0/tetrigo_0.2.0_darwin_all.tar.gz"
    sha256 "79db9f5f52c0654d06a72839b5815880b9d2dc9e8bb8f1f213db1e49d7e35089"

    def install
      bin.install "tetrigo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Broderick-Westrope/tetrigo/releases/download/v0.2.0/tetrigo_0.2.0_linux_amd64.tar.gz"
        sha256 "6c8d32b24cf77b2388fbfda6967752ab27a398ece3dfc48ae3c0a025914c3472"

        def install
          bin.install "tetrigo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Broderick-Westrope/tetrigo/releases/download/v0.2.0/tetrigo_0.2.0_linux_arm64.tar.gz"
        sha256 "b481104419133af184aa3d03a5ee01c973e0e1e6cd1b7f0a4192713db0bfaa8e"

        def install
          bin.install "tetrigo"
        end
      end
    end
  end
end
