# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tetrigo < Formula
  desc "Play Tetris in your terminal."
  homepage "https://www.westrope.dev/"
  version "0.2.0"

  on_macos do
    url "https://github.com/Broderick-Westrope/tetrigo/releases/download/v0.2.0/tetrigo_0.2.0_darwin_all.tar.gz"
    sha256 "26dc31bbab32ed32ad62595795b948a8ce00609a783ef1286d9301e7e28bd303"

    def install
      bin.install "tetrigo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Broderick-Westrope/tetrigo/releases/download/v0.2.0/tetrigo_0.2.0_linux_amd64.tar.gz"
        sha256 "33447244393d15c58e39907b28977cb96b4861e3331d7d6c2d717cc1936aec5b"

        def install
          bin.install "tetrigo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Broderick-Westrope/tetrigo/releases/download/v0.2.0/tetrigo_0.2.0_linux_arm64.tar.gz"
        sha256 "b62e409d9222d632c1b2e445c1eec843c54fa9c657f4809a7d53e3d4f970191f"

        def install
          bin.install "tetrigo"
        end
      end
    end
  end
end
